const mongoose = require('mongoose')
const { model, Schema } = mongoose

const champSchema = new Schema({
	version: String,
	id: String,
	key: String,
	name: String,
	title: String,
	blurb: String,
	lore: String,
	info: {
		attack: Number,
		defense: Number,
		magic: Number,
		difficulty: Number,
	},
	image: {
		full: String,
		sprite: String,
		group: String,
		x: Number,
		y: Number,
		w: Number,
		h: Number,
	},
	tags: [String],
	partype: String,
	stats: {
		hp: Number,
		hpperlevel: Number,
		mp: Number,
		mpperlevel: Number,
		movespeed: Number,
		armor: Number,
		armorperlevel: Number,
		spellblock: Number,
		spellblockperlevel: Number,
		attackrange: Number,
		hpregen: Number,
		hpregenperlevel: Number,
		mpregen: Number,
		mpregenperlevel: Number,
		crit: Number,
		critperlevel: Number,
		attackdamage: Number,
		attackdamageperlevel: Number,
		attackspeedperlevel: Number,
		attackspeed: Number,
	},
	images: {
		loading: [String],
		avatar: [String],
		spell: [String],
		splash: [String],
		passive: [String],
	},
	spells: [
		{
			id: String,
			name: String,
			description: String,
			tooltip: String,
			leveltip: {
				label: [String],
				effect: [String],
			},
			maxrank: Number,
			cooldown: [Number],
			cooldownBurn: String,
			cost: [Number],
			costBurn: String,
			datavalues: {},
			effect: [Array || null],
			effectBurn: [String],
			vars: [],
			costType: String,
			maxammo: String,
			range: [Number],
			rangeburn: String,
			image: {
				full: String,
				sprite: String,
				group: String,
				x: Number,
				y: Number,
				w: Number,
				h: Number,
			},
			resource: String,
		},
	],
	passive: {
		name: String,
		description: String,
		image: {
			full: String,
			sprite: String,
			group: String,
			x: Number,
			y: Number,
			w: Number,
			h: Number,
		},
	},
	skins: [
		{
			id: String,
			num: Number,
			name: String,
			chromas: Boolean,
		},
	],
	allytips: [String],
	enemytips: [String],
	partype: String,
	recommended: [],
})

const Champ = model('champions', champSchema)

module.exports = Champ
